Prepared os_config_policy for inclusion in C.G.C. documentation. Intending to use this snippet on the following page: https://cloud.google.com/compute/docs/os-configuration-management/create-os-policy-assignment
terraform-google-modules/terraform-docs-samples pull request #365
Opened 2023-03-20 14:56 UTC by rajasnathak

## Description

Fixes #218320463

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist
  
**Readiness**

- [x] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**
  
- [x] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x] My sample follows the other requirements and best practices in the [Contributing 
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)
  
**Testing**
  
- [x] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):
  
   - [x] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [x] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check
  
**Intended location**
  
- [x] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s): https://cloud.google.com/compute/docs/os-configuration-management/create-os-policy-assignment

- [ ] No, this sample won't be included on cloud.google.com
      Reason:
  
**API enablement**

- [ ] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [ ] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

2023-03-20 15:03 UTC, msampathkumar commented on os_config_policy/main.tf
> +# Sample OS policy based on example - https://cloud.google.com/compute/docs/os-configuration-management/working-with-os-policies#example-2
This URL is different from what is mentioned in the PR title.

https://cloud.google.com/compute/docs/os-configuration-management/create-os-policy-assignment

2023-03-20 21:35 UTC, rajasnathak commented
Seems like it failed due to an unrelated issue

2023-03-22 14:39 UTC, msampathkumar requested changes
Please update the sample location. Move it to `compute` folder.

2023-03-22 14:50 UTC, msampathkumar approved these changes
LGTM

2023-03-22 15:09 UTC, merged