Create main.tf
terraform-google-modules/terraform-docs-samples pull request #457
Opened 2023-07-11 18:05 UTC by davide-zanon

Adding file to create single-project reservations by specifying properties directly.

## Description

Fixes #<ISSUE-NUMBER>

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist

**Readiness**

- [ ] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [ ] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [ ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [ ] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [ ] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [ ] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s):

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [ ] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [ ] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

2023-07-13 15:58 UTC, msampathkumar commented
All tests are passing. Nice work.

Overall, PR LGTM but please fix the conventionalcommit message error.

2023-07-14 13:19 UTC, msampathkumar approved these changes

2023-08-03 16:07 UTC, gericdong approved these changes
LGTM

2023-08-03 16:09 UTC, rogerthatdev requested changes

2023-08-03 16:09 UTC, rogerthatdev commented on compute/reservation/create_local/main.tf
> +resource "google_compute_reservation" "deafult" {
Fix typo in `default`

2023-08-03 16:11 UTC, msampathkumar commented
/gcbrun

2023-08-03 16:15 UTC, msampathkumar commented
I fixed the spell-check issues. Approvals are done.

Requester did not request to Merge PR on approval. So, marking this PR as `Waiting response`

2023-08-09 10:15 UTC, msampathkumar commented
/gcbrun

2023-08-18 21:31 UTC, rogerthatdev approved these changes

2023-08-18 21:41 UTC, merged