Added documentation for cloud sql psc connectivity
terraform-google-modules/terraform-docs-samples pull request #489
Opened 2023-09-05 06:50 UTC by isaurabhuttam

## Description

Fixes #<ISSUE-NUMBER>

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist

**Readiness**

- [ ] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [ ] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [ ] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [ ] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [ ] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [ ] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s):

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [ ] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [ ] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

2023-09-06 16:28 UTC, enocom approved these changes

2023-09-11 17:09 UTC, rogerthatdev commented on cloud_sql/instance_psc/main.tf
Please split this sample into 2 separate `main.tf` files (eg `cloud_sql/mysql_instance_psc/main.tf` and `cloud_sql/postgres_instance_psc/main.tf`)

see #443

2023-09-11 17:11 UTC, rogerthatdev commented on cloud_sql/instance_psc/main.tf
> +resource "google_sql_database_instance" "postgres_instance_psc" {
After splitting the file, rename each `google_sql_database_instance` to `default` per samples' best practice guidelines.

2023-09-11 17:12 UTC, rogerthatdev requested changes
Let's split this sample like the other cloud_sql samples

2023-09-14 10:27 UTC, msampathkumar commented
As mentioned by @rogerthatdev, kindly use DB specific folder prefixes.

* mysql_instance_...
* postgres_instance_...

https://github.com/terraform-google-modules/terraform-docs-samples/tree/main/cloud_sql

2023-09-19 05:48 UTC, isaurabhuttam commented on cloud_sql/instance_psc/main.tf
Done.

2023-09-25 17:30 UTC, msampathkumar commented
/gcbrun

Re-triggering the CICD pipeline

2023-09-25 17:32 UTC, msampathkumar commented on cloud_sql/mysql_instance_psc/main.tf
> +resource "google_sql_database_instance" "main" {
```suggestion
resource "google_sql_database_instance" "default" {
```

Kindly use `default` as the default name for resource.

2023-09-25 17:32 UTC, msampathkumar commented on cloud_sql/mysql_instance_psc/main.tf
> +  name         = "psc-compute-address-${google_sql_database_instance.main.name}"
```suggestion
resource "google_compute_address" "default" {
  name         = "psc-compute-address-${google_sql_database_instance.default.name}"
```

2023-09-25 17:33 UTC, msampathkumar commented on cloud_sql/mysql_instance_psc/main.tf
> +  name = resource.google_sql_database_instance.main.name
```suggestion
data "google_sql_database_instance" "default" {
  name = resource.google_sql_database_instance.default.name
```

2023-09-29 16:39 UTC, rogerthatdev approved these changes
After a few minor changes, these samples individually pass int tests.

2023-09-29 16:39 UTC, merged