Added documentation for cloud sql instance edition
terraform-google-modules/terraform-docs-samples pull request #491
Opened 2023-09-07 07:59 UTC by ibhaskar2

## Description
Added documentation for cloud sql instance edition

Fixes #<ISSUE-NUMBER>

Note: If you are not associated with Google, open an issue for discussion before submitting a pull request.

## Checklist

**Readiness**

- [X] Yes, **merge** this PR after it is approved
- [ ] No, don't **merge** this PR after it is approved

**Style**

- [X] My sample follows the rules described for Terraform in the [Effective Samples style guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [X] My sample follows the other requirements and best practices in the [Contributing
guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#other-requirements-and-best-practices)

**Testing**

- [X] I have performed tests described in the [Contributing guide](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md):

   - [X] **[Tests](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#set-up-the-test-environment)** pass: `terraform apply`
   - [X] **[Lint](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/CONTRIBUTING.md#linting-and-formatting)** pass: `terraform fmt` check

**Intended location**

- [X] Yes, this sample will be (or already is) included on cloud.google.com
      Location(s):https://cloud.google.com/sql/docs/editions-intro

- [ ] No, this sample won't be included on cloud.google.com
      Reason:

**API enablement**

- [ ] If the sample needs an API enabled to pass testing, I have added the service to the [Test setup file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/test/setup/main.tf)

**Review**

- [ ] If this sample adds a new directory, I have added codeowners to the [CODEOWNERS file](https://github.com/terraform-google-modules/terraform-docs-samples/blob/main/.github/CODEOWNERS)

2023-09-07 13:05 UTC, gericdong commented
@ibhaskar2 please fix the lint and test errors when you have a chance. Thanks.

2023-09-07 15:32 UTC, enocom approved these changes

2023-09-07 15:32 UTC, enocom commented on cloud_sql/instance_edition
> +# [END cloud_sql_enterprise_instance]
nit missing newline

2023-09-11 05:39 UTC, ibhaskar2 commented on cloud_sql/instance_edition
> +# [END cloud_sql_enterprise_instance]
Fixed it

2023-09-11 17:17 UTC, rogerthatdev requested changes
please add the sample to `main.tf` file in the `cloud_sql/instance_edition/` directory.

2023-09-14 11:59 UTC, ibhaskar2 commented
@rogerthatdev please review it, i have made required changes

2023-09-18 16:57 UTC, msampathkumar commented
@ibhaskar2 Almost there! Use `mysql_` and `postgres_` prefixes in the folder names.

* cloud_sql/enterprise_edition_instance/main.tf --> cloud_sql/mysql_enterprise_edition_instance/main.tf

* cloud_sql/enterprise_plus_edition_instance/main.tf --> cloud_sql/postgres_enterprise_plus_edition_instance/main.tf

2023-09-18 16:57 UTC, msampathkumar commented
/gcbrun

2023-09-18 17:01 UTC, msampathkumar commented on cloud_sql/enterprise_edition_instance/main.tf
> +resource "google_sql_database_instance" "main" {
```suggestion
resource "google_sql_database_instance" "default" {
```

2023-09-18 17:01 UTC, msampathkumar commented on cloud_sql/enterprise_plus_edition_instance/main.tf
> +resource "google_sql_database_instance" "main" {
```suggestion
resource "google_sql_database_instance" "default" {
```

2023-09-18 19:41 UTC, ibhaskar2 commented on cloud_sql/enterprise_edition_instance/main.tf
> +resource "google_sql_database_instance" "main" {
Done

2023-09-18 19:42 UTC, ibhaskar2 commented on cloud_sql/enterprise_plus_edition_instance/main.tf
> +resource "google_sql_database_instance" "main" {
Done

2023-09-20 19:49 UTC, msampathkumar approved these changes
LGTM.

/gcbrun

2023-09-27 22:44 UTC, rogerthatdev approved these changes

2023-09-27 22:53 UTC, merged